# Generated by Django 2.2.12 on 2021-02-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SessionsPerPoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
        migrations.AlterModelTable(
            name='charging',
            table='charging',
        ),
        migrations.AlterModelTable(
            name='energyprovider',
            table='energy_provider',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='point',
            table='point',
        ),
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
        migrations.AlterModelTable(
            name='stationphones',
            table='station_phones',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userhascar',
            table='user_has_car',
        ),
        migrations.AlterModelTable(
            name='userphones',
            table='user_phones',
        ),
    ]
